create table if not exists users
(
    id    bigint generated by default as identity primary key,
    name  varchar(255) not null,
    email varchar(255) not null
);

comment on table users is 'Пользователи';

comment on column users.id is 'Идентификатор';
comment on column users.name is 'Имя';
comment on column users.email is 'Электронный адрес';