create table if not exists orders
(
    id          bigint generated by default as identity primary key,
    description varchar(255) not null,
    status      varchar(255) not null,
    user_id     bigint      not null
);

alter table if exists orders
    add constraint user_id_fk foreign key (user_id)
        references users (id);

comment on table orders is 'Заказы';

comment on column orders.id is 'Идентификатор';
comment on column orders.description is 'Описание';
comment on column orders.status is 'Статус';
comment on column orders.user_id is 'Идентификатор пользователя';